# Generated by Django 4.2.6 on 2023-12-01 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organization_owner'),
        ('userprofile', '0002_agent_organization_organizer_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(error_messages={'unique_together': 'Este usuario ya es agente de otra organización.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='organization',
            field=models.OneToOneField(error_messages={'unique_together': 'Este usuario ya es organizer de otra organización.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer', to='organization.organization'),
        ),
    ]
