# Generated by Django 4.2.6 on 2023-12-01 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organization_owner'),
        ('userprofile', '0003_alter_agent_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='organization.organization'),
        ),
    ]
