# Generated by Django 4.2.6 on 2023-12-01 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_agent_created_by_organizer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='created_by',
        ),
    ]
