# Generated by Django 4.2.6 on 2023-12-01 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0008_remove_organizer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_organizer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
