# Generated by Django 4.2.6 on 2023-12-06 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_name'),
        ('userprofile', '0009_organizer_created_at_organizer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(error_messages={'unique_together': 'Este usuario ya es agente de otra organización.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='organization.organization'),
        ),
    ]
