# Generated by Django 4.2.6 on 2023-12-02 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del país', max_length=100, unique=True)),
                ('code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^CO[A-Z]{3}$', 'El código debe empezar con CO seguido de tres mayúsculas')])),
                ('is_selected', models.BooleanField(default=False, help_text='Indica si el país está seleccionado')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(check=models.Q(('code__regex', '^CO[A-Z]{3}$')), name='El código debe empezar con CO seguido de tres mayúsculas'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('code',), name='Ese código de país ya existe.'),
        ),
    ]
