# Generated by Django 4.2.6 on 2023-12-02 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_name'),
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
            preserve_default=False,
        ),
    ]
