# Generated by Django 4.2.6 on 2023-12-06 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_country_organization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='country',
            name='Ese código de país ya existe.',
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^CO[A-Z]{3}$', 'El código debe empezar con CO seguido de tres mayúsculas')]),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Nombre del país', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('code', 'organization'), name='La combinación de código y organización debe ser única.'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='La combinación de nombre y organización debe ser única.'),
        ),
    ]
