# Generated by Django 4.2.6 on 2023-12-07 22:50

from django.db import migrations, models
import django.db.models.deletion
import operation.lead.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', max_length=254, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=models.SET(operation.lead.models.get_sentinel_user), related_name='assigned_lead', to='userprofile.agent')),
                ('created_by', models.ForeignKey(on_delete=models.SET(operation.lead.models.get_sentinel_user), related_name='created_lead', to='userprofile.agent')),
                ('last_modified_by', models.ForeignKey(on_delete=models.SET(operation.lead.models.get_sentinel_user), related_name='last_modified_lead', to='userprofile.agent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='organization.organization')),
            ],
        ),
    ]
