# Generated by Django 4.2.6 on 2023-12-09 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
        ('lead', '0005_alter_lead_primary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='stage.stage'),
        ),
    ]
