# Generated by Django 4.2.6 on 2023-12-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('lead', '0006_lead_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=models.ForeignKey(limit_choices_to={'is_selected': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.country'),
        ),
    ]
